title: D:\side\
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/blog/:num/"
url: http://dside.ru

collections:
  - upcoming

plugins:
- jekyll-paginate

kramdown:
  smart_quotes: lsaquo,rsaquo,laquo,raquo
  input: GFM
  mathjax: true

sass:
  style: :compressed
