title: D:\side\
quote: ...не так, как <wbr>xотелось бы.
markdown: kramdown
highlighter: pygments
permalink: /:title/
paginate: 5
paginate_path: "/blog/:num/"

kramdown:
  smart_quotes: lsaquo,rsaquo,laquo,raquo
  input: GFM

sass:
  style: :compressed
